apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <edit with the name of the service/pod>
  namespace: appservice-ns
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi