apiVersion: v1
kind: PersistentVolume
metadata:
  name: <edit with the name of the service/pod>
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


